version: 2
project_name: lgr
git:
  ignore_tags:
    - latest
before:
  hooks:
    - go mod download

builds:
  - id: default
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: arm
    main: "./main.go"
    binary: "lgr"
    ldflags:
      - -s -w
      - -X github.com/goliatone/lgr/pkg/version.Tag=v{{.Version}}
      - -X github.com/goliatone/lgr/pkg/version.Time={{.Date}}
      - -X github.com/goliatone/lgr/pkg/version.User=goliatone

universal_binaries:
  - id: lgr-universal
    name_template: "lgr"

archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^Update README"
      - "merge fix"
# brews:
#   - name: lgr
#     repository:
#       owner: goliatone
#       name: homebrew-tap
#       branch: master
#       token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
#     directory: Formula
#     description: pretty output for terminal scripts.
#     homepage: https://github.com/goliatone/lgr
#     license: "MIT"
#     test: |
#       system "#{bin}/lgr -V"
homebrew_casks:
  - name: lgr
    conflicts:
      - formula: lgr
    repository:
      owner: goliatone
      name: homebrew-tap
      branch: master
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Casks
    description: pretty output for terminal scripts.
    homepage: https://github.com/goliatone/lgr
    license: "MIT"

nfpms:
  - id: lgr
    file_name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    bindir: /usr/local/bin/
    maintainer: goliatone <lgr@goliat.one>
    description: pretty output for terminal scripts.
    homepage: https://github.com/goliatone/lgr
    license: "MIT"
    formats:
      - deb
      - rpm
