# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: lgr
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    # - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      # - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    main: "./cmd/lgr/main.go"
    binary: "lgr"
    ldflags:
      - -s -w
      - -X github.com/goliatone/lgr/pkg/version.Tag=v{{.Version}}
      - -X github.com/goliatone/lgr/pkg/version.Time={{.Date}}
      - -X github.com/goliatone/lgr/pkg/version.User=goliatone
archives:
  - replacements:
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^Update README"
      - "merge fix"
brews:
  - name: lgr
    tap:
      owner: goliatone
      name: homebrew-tap
    description: run commands in an environment defined using a ini configuration file.
    homepage: https://github.com/goliatone/lgr
    license: "MIT"
    test: |
      system "#{bin}/lgr -V"
nfpms:
  - id: lgr
    replacements:
      386: i386
      amd64: x86_64
    bindir: /usr/local/bin/
    maintainer: goliatone <lgr@goliat.one>
    description: run commands in an environment defined using a ini configuration file.
    homepage: https://github.com/goliatone/lgr
    license: "MIT"
    formats:
      - deb
      - rpm