# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
version: 2
project_name: lgr
git:
  ignore_tags:
    - latest
before:
  hooks:
    - go mod download

builds:
  - id: linux-windows
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      # - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    main: "./main.go"
    binary: "lgr"
    ldflags:
      - -s -w
      - -X github.com/goliatone/lgr/pkg/version.Tag=v{{.Version}}
      - -X github.com/goliatone/lgr/pkg/version.Time={{.Date}}
      - -X github.com/goliatone/lgr/pkg/version.User=goliatone

  - id: macos
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64  # intel macs
      - arm64  # Apple silicon
    main: "./main.go"
    binary: "lgr"
    ldflags:
      - -s -w
      - -X github.com/goliatone/lgr/pkg/version.Tag=v{{.Version}}
      - -X github.com/goliatone/lgr/pkg/version.Time={{.Date}}
      - -X github.com/goliatone/lgr/pkg/version.User=goliatone

universal_binaries:
  - id: lgr-universal
    ids:
      - macos
    name_template: "lgr"

archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^Update README"
      - "merge fix"

brews:
  - name: lgr
    repository:
      owner: goliatone
      name: homebrew-tap
      branch: master
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    description: pretty output for terminal scripts.
    homepage: https://github.com/goliatone/lgr
    license: "MIT"
    test: |
      system "#{bin}/lgr -V"
    ids:
      - macos
      - linux-windows

nfpms:
  - id: lgr
    builds:
      - linux-windows
    file_name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    bindir: /usr/local/bin/
    maintainer: goliatone <lgr@goliat.one>
    description: pretty output for terminal scripts.
    homepage: https://github.com/goliatone/lgr
    license: "MIT"
    formats:
      - deb
      - rpm
